FROM node:18-alpine

WORKDIR /app

COPY backend/package*.json ./
RUN npm install

COPY backend ./backend
COPY frontend ./frontend

WORKDIR /app/backend

ENV PORT=5000
EXPOSE 5000

CMD ["node", "index.js"]
