FROM node:18-alpine

# Install build tools for sqlite3
RUN apk add --no-cache make gcc g++ python3

# Set working dir to backend
WORKDIR /app/backend

# Install dependencies
COPY backend/package*.json ./
RUN npm install

# Copy backend source
COPY backend/ ./

# Copy frontend
WORKDIR /app
COPY frontend ./frontend

# Run server
WORKDIR /app/backend
EXPOSE 5000
CMD ["node", "index.js"]
